title: Think outside the fox
description: "A place where I talk to myself. But you can listen, too."
author:
  name: "oattao"
  email: "hoang.duy.tang@gmail.com"
  url: "https://oattao.github.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "oattao"
year : "2200"
